# 开发环境：使用docker-compose启动依赖中间件，在IDEA中启动微服务
# 创建网桥
networks:
  magic-network:
    external: false

services:
  magic-nacos:
    image: nacos/nacos-server:v2.4.0
    container_name: magic-nacos
    hostname: magic-nacos
    ports:
      - "8848:8848"
      - "9848:9848" # 服务需要通过localhost访问到9848 9849
      - "9849:9849"
    networks:
      - magic-network
    restart: no
    environment:
      MODE: standalone
      TZ: Asia/Shanghai

  magic-mysql:
    # 业务数据库
    image: mysql:8.4
    container_name: magic-mysql
    hostname: magic-mysql
    ports:
      - "3306:3306"
    networks:
      - magic-network
    environment:
      LANG: C.UTF-8 # 中文乱码-1
      # 数据库密码
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
#      - $MYSQL_DATA:/var/lib/mysql
      - $MYSQL_INIT:/docker-entrypoint-initdb.d/
    # 中文乱码-2
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  magic-auth-redis:
    # 鉴权中间件redis
    image: redis:7.4-alpine
    container_name: magic-auth-redis
    hostname: magic-auth-redis
    restart: no
    ports:
      - "6379:6379"
    networks:
      - magic-network
    environment:
      TZ: Asia/Shanghai

  magic-redis:
    # 鉴权中间件redis
    image: redis:7.4-alpine
    container_name: magic-redis
    hostname: magic-redis
    restart: no
    ports:
      - "6389:6379"
    networks:
      - magic-network
    environment:
      TZ: Asia/Shanghai

  magic-rabbitmq:
    image: rabbitmq:3-management
    container_name: magic-rabbitmq
    hostname: magic-rabbitmq
    restart: no
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magic-network
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: xiaolin
      RABBITMQ_DEFAULT_PASS: 123456rabbit
      RABBITMQ_DEFAULT_VHOST: /dev-media

  magic-multimedia-minio:
    image: minio/minio
    container_name: magic-multimedia-minio
    ports:
      - "9010:9000"
      - "9011:9001"
    networks:
      - magic-network
    volumes:
      - $MULTIMEDIA_MINIO_DATA:/data
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: xiaolin123minio
    command: server /data --console-address ":9001"

  magic-has-minio:
    image: minio/minio
    container_name: magic-has-minio
    ports:
      - "9020:9000"
      - "9021:9001"
    networks:
      - magic-network
    volumes:
      - $HAS_MINIO_DATA:/data
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: xiaolin123minio
    command: server /data --console-address ":9001"

  # 可观测性

  magic-loki-minio:
    image: minio/minio
    container_name: magic-loki-minio
    ports:
      - "9030:9000"
      - "9031:9001"
    networks:
      - magic-network
    volumes:
      - $LOKI_MINIO_DATA:/data
    environment:
      TZ: Asia/Shanghai
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: xiaolin123minio
    command: server /data --console-address ":9001"

  # Grafana
  # 默认端口 3000
  magic-grafana:
    image: grafana/grafana:11.3.2-ubuntu
    container_name: magic-grafana
    networks:
      - magic-network
    ports:
      - "19000:3000"
    volumes:
      - ./volume/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./volume/grafana/provisioning/etc/datasources:/etc/grafana/provisioning/datasources:ro
      - ./volume/grafana/provisioning/etc/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./volume/grafana/provisioning/var/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      # 中国时区、匿名登陆
      TZ: Asia/Shanghai
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_USERS_ALLOW_SIGN_UP: false

  # Prometheus
  magic-prometheus:
    image: prom/prometheus:v2.53.3
    container_name: magic-prometheus
    volumes:
      # 设置目录挂载
      - ./volume/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    environment:
      TZ: Asia/Shanghai
    networks:
      - magic-network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml" # prometheus配置文件
      - "--storage.tsdb.path=/prometheus" # prometheus数据存储路径

  # Grafana Alloy - 替代 Promtail
  magic-alloy:
    image: grafana/alloy:latest
    container_name: magic-alloy
    volumes:
      # 设置目录挂载
      - ./volume/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - ./logs:/var/log
    environment:
      TZ: Asia/Shanghai
    networks:
      - magic-network
    command:
      - "run"
      - "/etc/alloy/config.alloy"
      - "--server.http.listen-addr=0.0.0.0:12345"
    depends_on:
      - magic-loki

  # Loki
  magic-loki:
    image: grafana/loki:3.4
    container_name: magic-loki
    volumes:
#      - ./volume/loki/loki-local-config.yaml:/etc/loki/local-config.yaml:ro
      - ./volume/loki/loki-s3-config.yaml:/etc/loki/s3-config.yaml:ro
    environment:
      TZ: Asia/Shanghai
    networks:
      - magic-network
    command:
#      - "--config.file=/etc/loki/local-config.yaml"
      - "--config.file=/etc/loki/s3-config.yaml"
