# 创建网桥
networks:
  magic-network:
    external: false

services:
  magic-nacos:
    image: nacos/nacos-server:v2.4.0
    container_name: magic-local-nacos
    hostname: magic-local-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    networks:
      - magic-network
    restart: no
    environment:
      MODE: standalone
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime

  magic-mysql:
    # 业务数据库
    image: mysql:8.4
    container_name: magic-local-mysql
    hostname: magic-local-mysql
    ports:
      - "3306:3306"
    networks:
      - magic-network
    environment:
      LANG: C.UTF-8 # 中文乱码-1
      # 数据库密码
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./static/mysql:/docker-entrypoint-initdb.d/
    # 中文乱码-2
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  magic-redis:
    # 鉴权中间件redis
    image: redis:7.4-alpine
    container_name: magic-local-auth-redis
    hostname: magic-local-auth-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - magic-network

  magic-rabbitmq:
    image: rabbitmq:3-management
    container_name: magic-local-rabbitmq
    hostname: magic-local-rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: xiaolin
      RABBITMQ_DEFAULT_PASS: 123456rabbit
      RABBITMQ_DEFAULT_VHOST: /local-media
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - magic-network

#  magic-auth:
#    image: xxl1997/magic-video:auth-0.0.1-SNAPSHOT
#    container_name: magic-local-auth
#    build:
#      context: ./auth
#      dockerfile: Dockerfile
#    hostname: magic-local-auth
#    restart: no
#    ports:
#      - "8999:8999"
#    networks:
#      - magic-network
#    depends_on:
#      - magic-nacos
#      - magic-mysql
#      - magic-rabbitmq
#      - magic-redis
#
#  magic-gateway:
#    image: xxl1997/magic-video:gateway-0.0.1-SNAPSHOT
#    container_name: magic-local-gateway
#    build:
#      context: ./gateway
#      dockerfile: Dockerfile
#    hostname: magic-local-gateway
#    restart: no
#    ports:
#      - "9001:9001"
#    networks:
#      - magic-network
#    depends_on:
#      - magic-auth
#
#  net_test:
#    image: alpine
#    container_name: net_test_container
#    depends_on:
#      - magic-auth
#    networks:
#      - magic-network
#    command: /bin/sh -c "while true; do sleep 3600; done"