server:
  port: 9001

spring:
  application:
    name: gateway

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

dubbo:
  application:
    qos-enable: false
