server:
  port: 9001

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


