# 设置启用的环境

server:
  port: 9002


file:
  root:
    dir: ${user.home}/magic-video-document

  image:
    dir: image/

  video:
    dir: video/


spring:
  application:
    name: multimedia

  rabbitmq:
    host: 47.94.104.34
    username: xiaolin
    password: 123456xxl
    virtual-host: /media
    connection-timeout: 15000

  data:
    redis:
      client-type: lettuce
      database: 0
      host: 47.94.104.34
      port: 6379
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8

# 腾讯云服务器，兼容MySQL 5.7版本
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456xxlBUPT
    url: jdbc:mysql://bj-cynosdbmysql-grp-0t58ywes.sql.tencentcdb.com:24183/dev_video?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&autoReconnect=true

  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB


  # Nacos配置
  cloud:
    nacos:
      server-addr: 111.229.38.208:8848
      discovery:
        cluster-name: BEIJING
        # 设置为非临时实例
        ephemeral: true
        # 设置命名空间
        namespace: e35500e1-2441-4001-b60f-3f7d55b16cb5

