# 设置启用的环境

server:
  port: 9002


file:
  root:
    dir: ${user.home}/magic-video-document

  image:
    dir: image/

  video:
    dir: video/
    bucket-name: vod-videos-xiaolin


app:
  core-size: 3
  max-pool-size: 4
  queue-capacity: 8
  thread-prefix: MediaThread-


spring:
  application:
    name: multimedia

  rabbitmq:
    host: 47.94.104.34
    username: xiaolin
    password: 123456xxl
    virtual-host: /media
    connection-timeout: 15000

  data:
    redis:
      client-type: lettuce
      database: 0
      host: 47.94.104.34
      port: 6379
      lettuce:
        pool:
          enabled: true
          max-active: 8
          max-idle: 8

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB


  # Nacos配置
  cloud:
    nacos:
      server-addr: 111.229.38.208:8848
      discovery:
        cluster-name: BEIJING
        # 设置为非临时实例
        ephemeral: true
        # 设置命名空间
        namespace: e35500e1-2441-4001-b60f-3f7d55b16cb5

alibaba:
  cloud:
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com


