
# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100

# 分布式环境下基础设置，Loki 支持多组件分开部署
common:
  # 一致性哈希环
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: tsdb
      object_store: s3
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
    wal_directory: /tmp/loki/wal
    cache_ttl: 24h
    max_streams_per_user: 1000
  aws:
#    s3: http://minio:xiaolin123minio@magic-loki-minio:9000/loki-bucket
    endpoint: http://magic-loki-minio:9000
    bucketnames: loki-bucket
    access_key_id: FQyqvrSWnM1HfJFfRBcg
    secret_access_key: EW2ELsrqzOMPEAZHdW0zrXGWMYdGICR1HdHip5mU
    s3forcepathstyle: true
