name: Maven Package

on:
#  release:
#    types: [created]
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      # 1. 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置 Java 环境
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. 基于 Maven 构建项目
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true

      # 4. 配置 DockerHub Token 认证
      - name: Login in DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # 5. 构建并推送各微服务镜像
      - name: Build and push Docker images
        run: |
          TAG=$(git rev-list --count HEAD)
          DOCKER_USER=${{ secrets.DOCKERHUB_USERNAME }}
          
          docker buildx build --platform linux/arm64,linux/amd64 -t $DOCKER_USER/magic-core:v0.$TAG core/. --push
          docker buildx build --platform linux/arm64,linux/amd64 -t $DOCKER_USER/magic-gateway:v0.$TAG gateway/. --push
